{{ Html::script('bower/Waves/dist/waves.js') }}
{{ Html::script('bower/select2/dist/js/select2.min.js') }}
{{ Html::script('bower/sweetalert2/dist/sweetalert2.min.js') }}
{{ Html::script('bower/moment/moment.js') }}
{{ Html::script('bower/bootstrap-daterangepicker/daterangepicker.js') }}
{{ Html::script('js/sidebarmenu.js') }}
{{ Html::script('js/custom.min.js') }}
{{ Html::script('js/script.js') }}
{{ Html::script('js/listen-call-noty.js') }}
